services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
  api-gateway:
    environment:
      - ConnectionStrings__Redis=${REDIS_CONNECTION_STRING}
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.7
    command: start-dev --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/KeyCloak
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KC_ADMIN_CONSOLE_LOGIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_CONSOLE_PASSWORD}
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
    ports:
      - "8083:8080"
    depends_on:
      - keycloak-db
    volumes:
      - ./FrontEnd/mikeberries-frontend/dist_keycloak/keycloak-theme-for-kc-all-other-versions.jar:/opt/keycloak/providers/keycloak-theme.jar
      - ./FrontEnd/mikeberries-frontend/mikeberries_realm.json:/opt/keycloak/data/import/realm.json
  keycloak-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: KeyCloak
      POSTGRES_USER: ${KC_DB_USERNAME}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
    volumes:
      - keycloak_data:/var/lib/postgresql/data
  
  product-service:
    build:
      context: ./ProductService
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=${PRODUCT_SERVICE_DB_CONNECTION_STRING}
      - ConnectionStrings__Redis=${REDIS_CONNECTION_STRING}
      - Minio__ServiceUrl=${MINIO_SERVICE_URL}
      - Minio__DockerContainerUrl=${MINIO_DOCKER_CONTAINER_URL}
      - Minio__AccessKey=${MINIO_ACCESS_KEY}
      - Minio__SecretKey=${MINIO_SECRET_KEY}
      - Minio__BucketName=${MINIO_BUCKET_NAME}
      - Auth0__Authority=${AUTH0_AUTHORITY}
      - Auth0_Audience=${AUTH0_AUDIENCE}
    depends_on:
      product-service-DB:
        condition: service_healthy
      minio:
        condition: service_healthy
      redis:
        condition: service_healthy
  product-service-DB:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ProductServiceDB
    volumes:
      - product-service-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${postgres_user} -d ProductServiceDB"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  user-service:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - ConnectionStrings__DefaultConnection=${USER_SERVICE_DB_CONNECTION_STRING}
      - ConnectionStrings__Redis=${REDIS_CONNECTION_STRING}
    depends_on:
      user-service-DB:
        condition: service_healthy
  user-service-DB:
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: UserServiceDB
    volumes:
      - user-service-db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${postgres_user} -d UserServiceDB" ]
      interval: 5s
      timeout: 5s
      retries: 5
  
  order-service:
    build:
      context: ./OrderService
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      - ConnectionStrings__DefaultConnection=${ORDER_SERVICE_DB_CONNECTION_STRING}
    depends_on:
      order-service-DB:
        condition: service_healthy
  order-service-DB:
    image: postgres:16-alpine
    ports:
      - "5434:5432"
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: OrderServiceDB
    volumes:
      - order-service-db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${postgres_user} -d OrderServiceDB" ]
      interval: 5s
      timeout: 5s
      retries: 5
      
volumes:
  product-service-db:
  user-service-db:
  order-service-db:
  minio_data:
  redis_data:
  keycloak_data:
