services:
  product_service_api:
    build:
      context: ./ProductService
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=${connection_string}
      - Minio__ServiceURL=${minio_service_url}
      - Minio__AccessKey=${minio_access_key}
      - Minio__SecretKey=${minio_secret_key}
      - Minio__BucketName=${minio_bucket_name}
    depends_on:
      postgreDB:
        condition: service_healthy
      minio:
        condition: service_healthy
  postgreDB:
    image: postgres:16-alpine 
    restart: always
    environment:
      POSTGRES_USER: ${postgres_user}
      POSTGRES_PASSWORD: ${postgres_password}
      POSTGRES_DB: MikeBerriesDB
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${postgres_user} -d MikeBerriesDB"]
      interval: 5s
      timeout: 5s
      retries: 5
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  pgdata:
  minio_data:
  