name: ProductService CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  DOTNET_VERSION: '8.0.x'
  
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SONAR_PROJECT_KEY: "Baldj20_MikeBerries"
  SONAR_ORGANIZATION: "baldj20"
  SONAR_PROJECT_NAME: "ProductService"
  SONAR_EXCLUDE_FROM_COVERAGE: "**/Program.cs,**/Dockerfile,**/Migrations/**,**/ApiExtensions.cs,**/MikeBerriesDBContext.cs,**/Controllers/**,**/Repositories/**,**/Configurations/**,**/Result.cs,**/AuthorizationHandler.cs"

  BUILT_UNIT_TESTS_PATH: "./ProductService/ProductService.UnitTests/bin/Debug/net8.0/ProductService.UnitTests.dll"
  UNIT_TESTS_PROJECT_PATH: "./ProductService/ProductService.UnitTests/ProductService.UnitTests.csproj"

  BUILT_INTEGRATION_TESTS_PATH: "./ProductService/ProductService.IntegrationTests/bin/Debug/net8.0/ProductService.IntegrationTests.dll"
  INTEGRATION_TEST_PROJECT_PATH: "./ProductService/ProductService.IntegrationTests/ProductService.IntegrationTests.csproj"

  SOLUTION_PATH: "./ProductService/ProductService.sln"

  Minio__ServiceURL: "http://localhost:9000"
  Minio__AccessKey: ${{ secrets.MINIO_ACCESSKEY }}
  Minio__SecretKey: ${{ secrets.MINIO_SECRETKEY }}
  Minio__BucketName: ${{ secrets.MINIO_BUCKETNAME }}

  postgres_user: ${{ secrets.POSTGRES_USER }}
  postgres_password: ${{ secrets.POSTGRES_PASSWORD }}
  connection_string: ${{ secrets.CONNECTION_STRING }}

  Auth0__Authority: ${{ secrets.AUTH0_AUTHORITY }}
  Auth0__Audience: ${{ secrets.AUTH0_AUDIENCE }}

  ConnectionStrings__Redis: ${{ secrets.REDIS_CONNECTION_STRING }}
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      project_dir: ./ProductService 
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Start Infrastructure
        run: |
          docker compose up -d --wait postgreDB minio redis
          docker compose ps
            
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install Coverlet for .NET
        run: dotnet tool install --global coverlet.console

      - name: Install SonarScanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner
      
      - name: SonarQube Begin Analysis
        run: |
          dotnet sonarscanner begin \
            /k:"$SONAR_PROJECT_KEY" \
            /o:"$SONAR_ORGANIZATION" \
            /d:sonar.token="$SONAR_TOKEN" \
            /d:sonar.cs.opencover.reportsPaths=coverage_unit_tests.xml,coverage_integration_tests.xml \
            /d:sonar.coverage.exclusions=$SONAR_EXCLUDE_FROM_COVERAGE

          dotnet build "$SOLUTION_PATH" --no-incremental

          coverlet "$BUILT_UNIT_TESTS_PATH" \
            --target "dotnet" \
            --targetargs "test \"$UNIT_TESTS_PROJECT_PATH\" --no-build" \
            -f opencover \
            -o "coverage_unit_tests.xml"

          coverlet "$BUILT_INTEGRATION_TESTS_PATH" \
            --target "dotnet" \
            --targetargs "test \"$INTEGRATION_TEST_PROJECT_PATH\" --no-build" \
            -f opencover \
            -o "coverage_integration_tests.xml"

          dotnet sonarscanner end \
            /d:sonar.token="$SONAR_TOKEN"
