name: UserService CI
on:
  push:
    branches:
      - main
    paths:
      - 'UserService/**'
  pull_request:
    branches:
      - main
    paths:
      - 'UserService/**'
env:
  DOTNET_VERSION: '8.0.x'
  
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SONAR_PROJECT_KEY: "Baldj20_MikeBerries"
  SONAR_ORGANIZATION: "baldj20"
  SONAR_PROJECT_NAME: "UserService"
  SONAR_EXCLUDE_FROM_COVERAGE: "**/Program.cs,**/Dockerfile,**/UserService.DAL/**"

  SOLUTION_PATH: "./UserService/UserService.sln"
jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v3          
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install SonarScanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner
      
      - name: SonarQube Begin Analysis
        run: |
          dotnet sonarscanner begin \
            /k:"$SONAR_PROJECT_KEY" \
            /o:"$SONAR_ORGANIZATION" \
            /d:sonar.token="$SONAR_TOKEN" \
            /d:sonar.cs.opencover.reportsPaths=coverage.xml \
            /d:sonar.coverage.exclusions=$SONAR_EXCLUDE_FROM_COVERAGE

          dotnet build "$SOLUTION_PATH" --no-incremental

          dotnet sonarscanner end \
            /d:sonar.token="$SONAR_TOKEN"
